@address={{$dotenv %ADDRESS}}
@tokenAddress=0x6B175474E89094C44Da98b954EedeAC495271d0F
@api_key={{$dotenv %API_KEY}}

### Get Wallet Transaction History
GET https://deep-index.moralis.io/api/v2.2/wallets/{{address}}/history?chain=eth&order=DESC
accept: application/json
X-API-Key: {{api_key}} 

### Get ERC20 token price
GET https://deep-index.moralis.io/api/v2.2/erc20/{{tokenAddress}}/price?chain=eth&include=percent_change
accept: application/json
X-API-Key: {{api_key}} 