@address={{$dotenv %ADDRESS}}
@api_key={{$dotenv %API_KEY}}

### Get Wallet Transaction History
GET https://deep-index.moralis.io/api/v2.2/wallets/{{address}}/history?chain=eth&order=DESC
accept: application/json
X-API-Key: {{api_key}} 

